"""add challenges

Revision ID: 60432c9d0e1d
Revises: e4c347acc122
Create Date: 2026-09-12 15:29:56.539282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60432c9d0e1d'
down_revision: Union[str, Sequence[str], None] = 'e4c347acc122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('hints', sa.JSON(), nullable=True),
    sa.Column('flag_hash', sa.String(length=64), nullable=True),
    sa.Column('flag_format', sa.String(length=120), nullable=True),
    sa.Column('environment_type', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_author_id'), 'challenges', ['author_id'], unique=False)
    op.create_index(op.f('ix_challenges_slug'), 'challenges', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenges_slug'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_author_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
